# Generated by Django 5.1.7 on 2025-04-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_application_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='email',
            new_name='Email',
        ),
    ]
