# Generated by Django 5.1.7 on 2025-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_email_application_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Email',
            field=models.EmailField(default='Adresse e-mail', max_length=254),
        ),
    ]
