# Generated by Django 5.2 on 2025-04-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_application_jobpost_jobseeker_recruiter_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='profession',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
