# Generated by Django 5.2 on 2025-04-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=100)),
                ('jobPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.jobpost')),
                ('jobSeeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to='base.jobseeker')),
            ],
            options={
                'unique_together': {('jobPost', 'jobSeeker')},
            },
        ),
    ]
