# Generated by Django 5.2 on 2025-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_jobpost_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5+ years)'), ('executive', 'Executive Level')], default='mid', max_length=20, verbose_name='Experience Level Required'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_education',
            field=models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], default='bachelor', max_length=20, verbose_name='Minimum Education Required'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='show_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=2, verbose_name='Minimum Years of Experience'),
        ),
    ]
