# Generated by Django 5.2 on 2025-05-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_jobpost_experience_level_jobpost_min_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='years_of_experience',
        ),
    ]
