# Generated by Django 5.2 on 2025-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_jobpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='show_salary',
            field=models.CharField(choices=[('SHOW', 'Show salary'), ('HIDE', 'Hide salary')], max_length=20),
        ),
    ]
