# Generated by Django 5.2 on 2025-05-08 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_application_jobpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.jobpost'),
        ),
        migrations.AlterField(
            model_name='application',
            name='jobSeeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.jobseeker'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.resume'),
        ),
    ]
